Update git config workflow

diff --git a/warp/.warp/workflows/git-config-jmetrikat.yml b/warp/.warp/workflows/git-config-jmetrikat.yml
--- a/warp/.warp/workflows/git-config-jmetrikat.yml
+++ b/warp/.warp/workflows/git-config-jmetrikat.yml
@@ -5,22 +5,26 @@ command: |-
   git config user.email "{{email}}"
   git config user.signingkey {{signingkey}}
   git config commit.gpgsign {{gpgsign}}
+  git config core.hooksPath .githooks
+  echo "repos:\n  - repo: https://github.com/zricethezav/gitleaks\n    rev: v8.18.0\n    hooks:\n      - id: gitleaks" > .pre-commit-config.yaml
+  mkdir .githooks && echo '#!/usr/bin/env bash\n\nINSTALL_PYTHON=python3\nARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-push)\n\nHERE="$(cd "$(dirname "$0")" && pwd)"\nARGS+=(--hook-dir "$HERE" -- "$@")\n\nif command -v pre-commit > /dev/null; then\n    exec pre-commit "${ARGS[@]}"\nelif [ -x "$INSTALL_PYTHON" ]; then\n    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"\nelse\n    echo "`pre-commit` not found, install via `brew install pre-commit`." 1>&2\n    exit 1\nfi' > .githooks/pre-push
+  echo "[core]\n\thooksPath = .githooks\n[user]\n\temail = 120120832+jmetrikat@users.noreply.github.com\n\tname = Jannis Metrikat\n\tsigningkey = B223CAC5AAF85615\n[commit]\n\tgpgsign = true" > .gitconfig
 tags:
   - git
 description: "Configure git repository for @jmetrikat"
 arguments:
-    - name: name
-      description: The user name used for commits.
-      default_value: Jannis Metrikat
-    - name: email
-      description: The user email used for commits.
-      default_value: 120120832+jmetrikat@users.noreply.github.com
-    - name: signingkey
-      description: The key used for signing commits.
-      default_value: B223CAC5AAF85615
-    - name: gpgsign
-      description: Whether to sign commits with gpg.
-      default_value: true
+  - name: name
+    description: The user name used for commits.
+    default_value: Jannis Metrikat
+  - name: email
+    description: The user email used for commits.
+    default_value: 120120832+jmetrikat@users.noreply.github.com
+  - name: signingkey
+    description: The key used for signing commits.
+    default_value: B223CAC5AAF85615
+  - name: gpgsign
+    description: Whether to sign commits with gpg.
+    default_value: true
 source_url: "https://github.com/jmetrikat/dotfiles"
 author: Jannis Metrikat
 author_url: "https://github.com/jmetrikat"
